import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {adminUsersRoute} from '../src/admin/users.ts';
const key='isolated-admin-key-'.repeat(3);
function fixture(t){
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
 db.exec("INSERT INTO users(id,account,password_hash,email,created_at) VALUES('u1','alice','never-expose','alice@example.test','2026-01-01'),('u2','bob','never-expose','bob@example.test','2026-01-02'),('u3','carl','never-expose','carl@example.test','2026-01-03')");
 db.exec("INSERT INTO subscriptions(user_id,plan_name,expires_at,updated_at) VALUES('u2','pro','2099-01-01T00:00:00.000Z','v1'),('u3','pro','2001-01-01T00:00:00.000Z','v1')");
 const ym=new Date().toISOString().slice(0,7);db.prepare('INSERT INTO usage_monthly VALUES(?,?,1234,100000,7)').run('u1',ym);
 const prepare=sql=>{let args=[];return {bind(...values){args=values;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:db.prepare(sql).run(...args)}}}};
 const DB={prepare,async batch(statements){db.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.all());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}};
 const call=(path='',body,credential=key)=>adminUsersRoute(new Request('https://isolated.test/v1/admin/users'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+credential,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),{DB,ADMIN_API_KEY:key});
 const change=async(id='u1',extra={})=>{const {user}=await (await call('/'+id)).json();return {plan_name:'pro',expires_at:'2099-01-01T00:00:00.000Z',reason:'客服核实后补偿会员',version:user.version,request_id:crypto.randomUUID(),...extra}};
 return {db,call,change,ym};
}
test('admin users rejects account credentials without disclosing data',async t=>{const {call}=fixture(t);for(const token of ['', 'ordinary-user-session',key+'x']){const r=await call('',undefined,token);assert.equal(r.status,401);assert.equal(r.headers.get('cache-control'),'no-store');}});
test('summary counts active memberships and actual monthly usage without private fields',async t=>{const {call}=fixture(t);const d=await (await call()).json();assert.deepEqual(d.summary,{total:3,members:1,used:1234,tasks:7});assert.equal(d.total,3);assert.ok(!JSON.stringify(d).includes('password'));for(const [status,id]of [['active','u2'],['expired','u3'],['free','u1']]){const data=await (await call('?status='+status)).json();assert.equal(data.total,1);assert.equal(data.items[0].id,id)}});
test('search treats wildcard input literally and validates pagination',async t=>{const {call}=fixture(t);assert.equal((await (await call('?q=alice')).json()).total,1);assert.equal((await (await call('?q=%25')).json()).total,0);assert.equal((await call('?page=-1')).status,400);assert.equal((await call('?status=unknown')).status,400);});
test('membership change audits and applies quota without changing consumption or orders',async t=>{const {call,change,db,ym}=fixture(t);const body=await change();assert.equal((await call('/u1/membership',body)).status,200);const sub=db.prepare("SELECT * FROM subscriptions WHERE user_id='u1'").get();assert.equal(sub.plan_name,'pro');assert.equal(sub.expires_at,body.expires_at);assert.equal(sub.auto_renew,0);assert.deepEqual({...db.prepare('SELECT chars_used,chars_quota,task_count FROM usage_monthly WHERE user_id=? AND year_month=?').get('u1',ym)},{chars_used:1234,chars_quota:1000000,task_count:7});const d=await (await call('/u1')).json();assert.equal(d.history.length,1);assert.equal(d.history[0].before_snapshot,'null');assert.equal(d.history[0].reason,body.reason);assert.ok(!JSON.stringify(d).includes(key));assert.equal(db.prepare('SELECT COUNT(*) n FROM orders').get().n,0);});
test('idempotent retry and mismatched request-id conflict',async t=>{const {call,change,db}=fixture(t);const body=await change();await call('/u1/membership',body);assert.equal((await (await call('/u1/membership',body)).json()).replayed,true);assert.equal((await call('/u1/membership',{...body,reason:'different reason'})).status,409);assert.equal(db.prepare('SELECT COUNT(*) n FROM admin_membership_changes_v3').get().n,1)});
test('stale admin cannot overwrite payment renewal',async t=>{const {call,change,db}=fixture(t);const body=await change('u2');db.exec("UPDATE subscriptions SET expires_at='2099-02-01T00:00:00.000Z',updated_at='payment-renewal' WHERE user_id='u2'");assert.equal((await call('/u2/membership',body)).status,409);assert.equal(db.prepare("SELECT expires_at FROM subscriptions WHERE user_id='u2'").get().expires_at,'2099-02-01T00:00:00.000Z');assert.equal(db.prepare('SELECT COUNT(*) n FROM admin_membership_changes_v3').get().n,0)});
test('failed quota update rolls back membership and audit',async t=>{const {call,change,db}=fixture(t);db.exec("CREATE TRIGGER fail_admin BEFORE UPDATE ON usage_monthly BEGIN SELECT RAISE(ABORT,'injected'); END;");assert.equal((await call('/u1/membership',await change())).status,503);assert.equal(db.prepare("SELECT COUNT(*) n FROM subscriptions WHERE user_id='u1'").get().n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM admin_membership_changes_v3').get().n,0)});
test('expired and revoked membership retains actual consumption',async t=>{const {call,change,db}=fixture(t);await call('/u1/membership',await change());await call('/u1/membership',await change('u1',{expires_at:'2001-01-01T00:00:00.000Z'}));assert.equal((await (await call('/u1')).json()).user.membership,'expired');await call('/u1/membership',await change('u1',{plan_name:'free',expires_at:null}));const d=await (await call('/u1')).json();assert.equal(d.user.membership,'free');assert.equal(d.user.used,1234);assert.equal(d.history.length,3);assert.equal(db.prepare("SELECT chars_quota FROM usage_monthly WHERE user_id='u1'").get().chars_quota,100000)});
test('invalid changes cannot mutate data',async t=>{const {call,change,db}=fixture(t);const body=await change();for(const patch of [{reason:' '},{plan_name:'enterprise'},{expires_at:'not-date'},{expires_at:'2099-02-31T00:00:00.000Z'},{plan_name:'free'},{request_id:'invalid'},{reason:'a'.repeat(5000)}])assert.equal((await call('/u1/membership',{...body,...patch})).status,400);assert.equal((await call('/missing/membership',body)).status,404);assert.equal(db.prepare('SELECT COUNT(*) n FROM admin_membership_changes_v3').get().n,0)});
