import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
test('D1 account actions: concurrent optimistic edits, audit union and revoked super quota',{timeout:60000},async t=>{
 const key='isolated-admin-account-d1-'.repeat(3);const script=process.env.ACCOUNT_CANDIDATE?readFileSync(process.env.ACCOUNT_CANDIDATE,'utf8'):(await (await import('esbuild')).build({entryPoints:[new URL('../src/index.ts',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'})).outputFiles[0].text;
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'accounts-test',modules:true,script,d1Databases:{DB:'accounts-isolated'},bindings:{ADMIN_API_KEY:key},compatibilityDate:'2026-09-13'}]}));t.after(()=>mf.dispose());const DB=await mf.getD1Database('DB','accounts-test');
 const schema=new DatabaseSync(':memory:');schema.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));const objects=schema.prepare("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'index' THEN 2 ELSE 3 END").all();const plans=schema.prepare('SELECT * FROM plan_catalog').all();schema.close();for(const o of objects)await DB.prepare(o.sql).run();for(const p of plans)await DB.prepare(`INSERT INTO plan_catalog(${Object.keys(p).join(',')}) VALUES(${Object.keys(p).map(()=>'?')})`).bind(...Object.values(p)).run();
 await DB.prepare("UPDATE plan_catalog SET quota=CASE id WHEN 'max' THEN 1000 ELSE 10 END").run();await DB.prepare("INSERT INTO users(id,account,password_hash,created_at) VALUES('u','u','unused','2026-01-01')").run();
 const call=(path,body)=>mf.dispatchFetch('https://local.test/v1/admin/'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+key,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 const detail=async()=>{const r=await call('users/u');assert.equal(r.status,200);return (await r.json()).user;};const change=async action=>({action,version:(await detail()).account_version,reason:'本地 D1 验证',request_id:crypto.randomUUID()});
 const b=await change('grant_super'),results=await Promise.all([call('users/u/account',b),call('users/u/account',{...b,action:'disable',request_id:crypto.randomUUID()})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);if(!(await detail()).is_active)await call('users/u/account',await change('enable'));if(!(await detail()).is_super)await call('users/u/account',await change('grant_super'));
 assert.equal((await detail()).plan_name,'max');const list=await call('users?status=super');assert.equal(list.status,200);assert.equal((await list.json()).items.length,1);
 const audit=await call('operations/audit');assert.equal(audit.status,200);assert.ok((await audit.json()).items.some(x=>x.kind==='账户 / u'));
 const ym=new Date().toISOString().slice(0,7);await DB.prepare("INSERT INTO usage_monthly VALUES('u',?,0,1000,0)").bind(ym).run();await call('users/u/account',await change('revoke_super'));
 await assert.rejects(DB.prepare("INSERT INTO translation_requests(user_id,request_id,payload_hash,year_month,reserved,expires_at) VALUES('u','r','hash',?,11,9999999999)").bind(ym).run(),/quota_exceeded/);
 await call('users/u/account',await change('delete'));assert.equal((await detail()).account_status,'deleted');await call('users/u/account',await change('restore'));assert.equal((await detail()).account_status,'disabled');
});
