import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/worker.mjs';
import {glossaryRoute} from '../src/account/glossary.ts';
function fixture(t) {
 const x=setup(t);
 const read=()=>x.db.prepare("SELECT entries_json,updated_at FROM user_glossaries WHERE user_id='alice'").get();
 const seed=(entries)=>x.db.prepare("INSERT OR REPLACE INTO user_glossaries VALUES('alice',?,'2026-09-16T00:00:00.000Z')").run(JSON.stringify(entries));
 const call=(body,readBody)=>glossaryRoute(new Request('https://test/v1/glossary',{method:body===undefined?'GET':'PUT'}),x.env,'alice','https://site.test',readBody||(()=>Promise.resolve(body)));
 return {...x,read,seed,call};
}
const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const saved={id,source:'法兰',target:'Flange',note:'工程备注',category:'机械',folder:'常用',enabled:false,extension:'retained'};
test('legacy APP upload preserves web ID/note and unknown stored metadata',async t=>{const x=fixture(t);x.seed([saved]);const r=await x.call({entries:[{source:'法兰',target:'Flange'}]});assert.equal(r.status,200);assert.deepEqual((await r.json()).entries,[saved]);});
test('unique source retains identity when translation changes',async t=>{const x=fixture(t);x.seed([saved]);const r=await x.call({entries:[{source:'法兰',target:'FLANGE',enabled:true}]});assert.equal(r.status,200);const e=(await r.json()).entries[0];assert.equal(e.id,id);assert.equal(e.note,saved.note);assert.equal(e.target,'FLANGE');assert.equal(e.enabled,true);});
test('explicit known ID permits source rename and intentional note clearing',async t=>{const x=fixture(t);x.seed([saved]);const r=await x.call({entries:[{id,source:'新法兰',target:'New flange',note:''}]});assert.equal(r.status,200);const e=(await r.json()).entries[0];assert.equal(e.id,id);assert.equal(e.note,'');assert.equal(e.folder,'常用');});
test('new and legacy ID-less entries receive stable server IDs on successful PUT',async t=>{const x=fixture(t);x.seed([{source:'管道',target:'Pipe'}]);const payload={entries:[{source:'管道',target:'Pipe'},{source:'法兰',target:'Flange'}]};const first=await(await x.call(payload)).json();const second=await(await x.call(payload)).json();assert.equal(new Set(first.entries.map(e=>e.id)).size,2);assert.deepEqual(first.entries.map(e=>e.id),second.entries.map(e=>e.id));});
test('stale revision rejects entire upload and leaves persisted bytes unchanged',async t=>{const x=fixture(t);x.seed([saved]);const original=await(await x.call()).json();assert.match(original.revision,/^[a-f0-9]{64}$/);assert.equal((await x.call({entries:[{...saved,note:'changed'}],expected_revision:original.revision})).status,200);const before=x.read();assert.equal((await x.call({entries:[],expected_revision:original.revision})).status,409);assert.deepEqual(x.read(),before);});
test('revision changes even when content unchanged and clock is fixed',async t=>{const x=fixture(t);x.seed([saved]);t.mock.method(Date,'now',()=>Date.parse('2026-09-16T00:00:00.000Z'));const a=await(await x.call()).json();const b=await(await x.call({entries:[saved],expected_revision:a.revision})).json();assert.notEqual(a.revision,b.revision);assert.ok(b.updated_at>a.updated_at);});
test('CAS rejects concurrent web mutation after read even without client revision',async t=>{const x=fixture(t);x.seed([saved]);let after;const r=await x.call({entries:[]},async()=>{x.seed([{...saved,note:'concurrent edit'}]);after=x.read();return {entries:[]};});assert.equal(r.status,409);assert.deepEqual(x.read(),after);});
test('CAS rejects first-writer race on previously empty account',async t=>{const x=fixture(t);const r=await x.call({entries:[]},async()=>{x.seed([saved]);return {entries:[]};});assert.equal(r.status,409);assert.equal(JSON.parse(x.read().entries_json)[0].note,saved.note);});
for(const entry of [null,[],{}, {source:42,target:'x'},{source:'  ',target:'x'}, {source:'x'.repeat(501),target:'y'}, {source:'x',target:'y'.repeat(501)}, {source:'x',target:'y',note:'n'.repeat(1001)}, {source:'x',target:'y',folder:'f'.repeat(129)}, {source:'x',target:'y',category:12}, {source:'x',target:'y',enabled:'false'}, {source:'x',target:'y',id:'invalid'}])
 test('invalid input is rejected without silent filtering/truncation: '+JSON.stringify(entry).slice(0,85),async t=>{const x=fixture(t);x.seed([saved]);const before=x.read();assert.equal((await x.call({entries:[entry]})).status,400);assert.deepEqual(x.read(),before);});
test('ambiguous legacy identity rejected rather than assigning wrong metadata',async t=>{const x=fixture(t);x.seed([saved,{...saved,id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',target:'Other flange',note:'different'}]);const before=x.read();assert.equal((await x.call({entries:[{source:'法兰',target:'New'}]})).status,409);assert.deepEqual(x.read(),before);});
test('unknown and duplicate explicit IDs cannot be accepted',async t=>{const x=fixture(t);x.seed([saved]);const before=x.read();for(const entries of [[{...saved,id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'}],[saved,{...saved,target:'Other'}]])assert.equal((await x.call({entries})).status,409);assert.deepEqual(x.read(),before);});
test('duplicate incoming pairs are rejected',async t=>{const x=fixture(t);assert.equal((await x.call({entries:[{source:'x',target:'y'},{source:'x',target:'y'}]})).status,409);assert.equal(x.read(),undefined);});
test('corrupt stored JSON is never hidden as empty or overwritten',async t=>{const x=fixture(t);x.db.prepare("INSERT INTO user_glossaries VALUES('alice','not-json','old')").run();const before=x.read();for(const body of [undefined,{entries:[]}]){const r=await x.call(body);assert.equal(r.status,409);assert.equal((await r.json()).error_code,'glossary_data_invalid');}assert.deepEqual(x.read(),before);});
test('malformed stored entries and duplicate identities preserve original data',async t=>{const x=fixture(t);for(const entries of [[null],[{target:'x'}],[saved,{...saved,target:'Other'}]]){x.seed(entries);const before=x.read();assert.equal((await x.call({entries:[]})).status,409);assert.deepEqual(x.read(),before);}});
test('whole-list capacity accepts 1000, rejects 1001 without mutation',async t=>{const x=fixture(t);const entries=Array.from({length:1000},(_,i)=>({source:'s'+i,target:'t'+i}));assert.equal((await x.call({entries})).status,200);const before=x.read();assert.equal((await x.call({entries:[...entries,{source:'extra',target:'extra'}]})).status,400);assert.deepEqual(x.read(),before);});
test('existing oversized glossary stays readable and cannot be silently shrunk',async t=>{const x=fixture(t);x.seed(Array.from({length:1001},(_,i)=>({source:'s'+i,target:'t'+i})));assert.equal((await(await x.call()).json()).entries.length,1001);const before=x.read();assert.equal((await x.call({entries:[]})).status,409);assert.deepEqual(x.read(),before);});
test('web and APP share 1000-entry capacity; existing items can still be removed',async t=>{const x=fixture(t);x.seed([saved,...Array.from({length:998},(_,i)=>({source:'s'+i,target:'t'+i}))]);const a=await x.login('web');const create=()=>x.request('/v1/terminology',{method:'POST',token:a.token,body:{source:'extra',target:'extra'}});assert.equal((await create()).status,201);const before=x.read();assert.equal((await x.request('/v1/terminology',{method:'POST',token:a.token,body:{source:'overflow',target:'overflow'}})).status,409);assert.deepEqual(x.read(),before);assert.equal((await x.request('/v1/terminology/'+id,{method:'DELETE',token:a.token})).status,200);});
test('APP upload metadata remains deletable from web and isolated from another account',async t=>{const x=fixture(t);x.seed([saved]);const a=await x.login('app'),b=await x.login('web','','bob');assert.equal((await x.request('/v1/glossary',{method:'PUT',token:a.token,body:{entries:[{source:'法兰',target:'Flange'}]}})).status,200);assert.equal((await(await x.request('/v1/glossary',{token:b.token})).json()).entries.length,0);assert.equal((await x.request('/v1/terminology/'+id,{method:'DELETE',token:b.token})).status,404);assert.equal((await x.request('/v1/terminology/'+id,{method:'DELETE',token:a.token})).status,200);});
test('invalid optional revision cannot cause a blind overwrite',async t=>{const x=fixture(t);x.seed([saved]);const before=x.read();for(const expected_revision of [null,123,'invalid'])assert.equal((await x.call({entries:[],expected_revision})).status,400);assert.deepEqual(x.read(),before);});

test('legacy ID-less GET has stable distinct identities and PATCH preserves unselected records',async t=>{
 const x=fixture(t);x.seed([{source:'旧词',target:'Old'},{source:'旧词',target:'Old'}]);
 const before=x.read(),a=await(await x.call()).json(),b=await(await x.call()).json();
 assert.deepEqual(a.entries.map(e=>e.id),b.entries.map(e=>e.id));assert.equal(new Set(a.entries.map(e=>e.id)).size,2);assert.deepEqual(JSON.parse(x.read().entries_json),a.entries);
 const entry={...a.entries[0],target:'Confirmed',source_lang:'ZH',target_lang:'EN',direction_pending:false};
 const body={version:2,expected_revision:a.revision,upserts:[entry],delete_ids:[]};
 const response=await glossaryRoute(new Request('https://test/v1/glossary',{method:'PATCH'}),x.env,'alice','https://site.test',async()=>body);
 assert.equal(response.status,200);const saved=await response.json();assert.equal(saved.entries.length,2);assert.deepEqual(saved.entries.find(e=>e.id===a.entries[1].id),a.entries[1]);
 const persisted=x.read();assert.equal((await x.call({entries:[]})).status,409);assert.deepEqual(x.read(),persisted);
});
