import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/worker.mjs';
import worker from '../src/index.ts';
const input={source_lang:'zh',target_lang:'en',items:[{id:0,text:'法兰'},{id:1,text:'钢板'}]};
async function translated(t,content){const x=setup(t),a=await x.login('app');let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;return Response.json({choices:[{message:{content:JSON.stringify(content)}}]});});const send=()=>worker.fetch(new Request('https://test/v1/translate',{method:'POST',headers:{authorization:'Bearer '+a.token,'content-type':'application/json','Idempotency-Key':'history-request-01'},body:JSON.stringify(input)}),x.env);return {...x,a,send,calls:()=>calls};}
const list=async(x,token)=>{const r=await x.request('/v1/translation/history',{token});assert.equal(r.status,200);return r.json();};
test('settled requests appear without usage_logs; replay has one history row and charge',async t=>{
 const x=await translated(t,[{id:0,translated_text:'Flange'},{id:1,translated_text:'Plate'}]);assert.equal((await x.send()).status,200);assert.equal((await x.send()).status,200);
 const web=await x.login('web'),h=await list(x,web.token);assert.equal(h.items.length,1);assert.equal(h.items[0].characters,4);assert.equal(h.items[0].status,'completed');assert.equal(x.calls(),1);
 assert.equal(x.db.prepare("SELECT chars_used FROM usage_monthly WHERE user_id='alice'").get().chars_used,4);
 assert.equal(x.db.prepare('SELECT count(*) AS n FROM usage_logs').get().n,0);
 assert.equal(h.items[0].source_language,'zh');assert.equal(h.items[0].target_language,'en');assert.equal(h.items[0].timestamp_kind,'recorded');assert.equal(h.items[0].created_at,h.items[0].started_at);assert.ok(Date.parse(h.items[0].completed_at)>=Date.parse(h.items[0].started_at));assert.equal(h.items[0].completion_kind,'recorded');assert.equal(h.items[0].download_url,null);
 assert.deepEqual(await(await x.request('/v1/translation/tasks/'+h.items[0].id,{token:web.token})).json(),h.items[0]);
 const bob=await x.login('web','','bob');assert.deepEqual((await list(x,bob.token)).items,[]);assert.equal((await x.request('/v1/translation/tasks/'+h.items[0].id,{token:bob.token})).status,404);
});
test('partial translation reports successful charge, not complete success',async t=>{const x=await translated(t,[{id:0,translated_text:'Flange'}]);await x.send();const row=(await list(x,x.a.token)).items[0];assert.equal(row.status,'partial');assert.equal(row.characters,2);assert.equal(row.requested_characters,4);});
test('provider failure is failed with zero charge, without leaking text',async t=>{const x=await translated(t,null);assert.equal((await x.send()).status,502);const h=await list(x,x.a.token);assert.equal(h.items[0].status,'failed');assert.equal(h.items[0].characters,0);assert.ok(!JSON.stringify(h).includes('法兰'));});
test('all missing results are failed',async t=>{const x=await translated(t,[]);await x.send();assert.equal((await list(x,x.a.token)).items[0].status,'failed');});
function seed(x,count){x.db.prepare("INSERT INTO usage_monthly VALUES('alice','2026-09',0,100000,0)").run();for(let i=0;i<count;i++){x.db.prepare("INSERT INTO translation_requests(user_id,request_id,payload_hash,year_month,reserved,expires_at) VALUES('alice',?,'h','2026-09',2,?)").run('request-'+String(i).padStart(4,'0'),Math.floor(Date.now()/1000)+180);}}
test('equal-timestamp pagination includes every record once and retains legacy logs',async t=>{const x=setup(t),a=await x.login('web');seed(x,105);x.db.prepare("INSERT INTO usage_logs(id,user_id,device_id,src_lang,tgt_lang,chars,created_at) VALUES('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','alice','d','zh','en',3,'2020-01-01T00:00:00Z')").run();let path='/v1/translation/history',ids=[];do{const r=await x.request(path,{token:a.token});assert.equal(r.status,200);const h=await r.json();ids.push(...h.items.map(x=>x.id));path=h.nextCursor?'/v1/translation/history?before='+encodeURIComponent(h.nextCursor):null;}while(path);assert.equal(ids.length,106);assert.equal(new Set(ids).size,106);assert.equal(ids.at(-1),'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');});
test('history never settles pending or expired requests or mutates billing',async t=>{const x=setup(t),a=await x.login('web');seed(x,2);x.db.prepare("UPDATE translation_requests SET expires_at=1 WHERE request_id='request-0000'").run();const before=x.db.prepare('SELECT * FROM usage_monthly').get();const h=await list(x,a.token);assert.deepEqual(new Set(h.items.map(x=>x.status)),new Set(['processing','expired']));assert.deepEqual(x.db.prepare('SELECT * FROM usage_monthly').get(),before);assert.equal(x.db.prepare("SELECT count(*) n FROM translation_requests WHERE state='reserved'").get().n,2);});
test('oversized cursor, absent detail and anonymous requests are rejected',async t=>{const x=setup(t),a=await x.login('web');assert.equal((await x.request('/v1/translation/history?before='+'x'.repeat(257),{token:a.token})).status,400);assert.equal((await x.request('/v1/translation/tasks/request_missing-record',{token:a.token})).status,404);assert.equal((await x.request('/v1/translation/history')).status,401);});

