import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/worker.mjs';
import {operationsRoute,settings,validSetting} from '../src/admin/operations.ts';
import {entitlementSnapshot} from '../src/entitlements.ts';
const key='operations-admin-test-key-'.repeat(3);
function fixture(t){const x=setup(t);x.env.ADMIN_API_KEY=key;const call=(path,body,credential=key)=>operationsRoute(new Request('https://local.test/v1/admin/operations/'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+credential},...(body?{body:JSON.stringify(body)}:{})}),x.env);return {...x,call};}
const release={latest_version:'2.1.1+ui.20260916',download_url:'https://example.com/app.zip',backup_download_url:'',release_notes:'版本说明 <script>不执行</script>'};
const patch=value=>({value,revision:1,reason:'测试管理员设置更新',request_id:crypto.randomUUID()});
test('operations auth rejects ordinary token; defaults preserve env and fallback download',async t=>{const x=fixture(t);assert.equal((await x.call('settings',undefined,'regular')).status,401);x.env.LATEST_VERSION='9.8.7';x.env.DOWNLOAD_URL='https://example.com/original.zip';assert.equal((await settings(x.env,'release')).latest_version,'9.8.7');assert.equal((await settings(x.env,'release')).download_url,x.env.DOWNLOAD_URL);const data=await(await x.call('settings')).json();assert.equal(data.items.length,3);assert.equal(data.items.find(i=>i.section==='controls').value.device_wait_days,20);});
test('release validates unsafe URLs, version and payload fields',async t=>{const x=fixture(t);for(const download_url of ['javascript:alert(1)','http://example.com/x','data:text/html,x','https://u:p@example.com/x','https://example.com/\\x'])assert.equal((await x.call('settings/release',patch({...release,download_url}))).status,400);for(const latest_version of ['2','<script>','a'.repeat(100)])assert.equal((await x.call('settings/release',patch({...release,latest_version}))).status,400);assert.equal((await x.call('settings/release',patch({...release,evil:true}))).status,400);});
test('configuration optimistic concurrency, audit and idempotency; public version sees saved values',async t=>{const x=fixture(t),body=patch(release);assert.equal((await x.call('settings/release',body)).status,200);assert.equal((await(await x.call('settings/release',body)).json()).replayed,true);assert.equal((await x.call('settings/release',{...body,request_id:crypto.randomUUID()})).status,409);assert.equal((await x.call('settings/release',{...body,reason:'不同操作原因'})).status,409);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM operation_changes').get().n,1);const version=await(await x.request('/v1/version')).json();assert.equal(version.download_url,release.download_url);assert.equal(version.mandatory,false);assert.equal((await(await x.call('audit')).json()).items.length,1);});
test('scheduled announcement visibility and content validation',async t=>{const x=fixture(t),c=await settings(x.env,'content');assert.equal(validSetting('content',{...c,announcement_start:'nonsense'}),false);assert.equal(validSetting('content',{...c,announcement_start:'2099-01-02T00:00:00.000Z',announcement_end:'2099-01-01T00:00:00.000Z'}),false);await x.call('settings/content',patch({...c,announcement:'未来公告',announcement_start:'2099-01-01T00:00:00.000Z'}));const d=await(await x.request('/v1/site')).json();assert.equal(d.content.announcement,'');assert.equal((await settings(x.env,'content')).announcement,'未来公告');});
test('control gates preserve existing login and public read paths',async t=>{const x=fixture(t);x.env.PAYMENTS_ENABLED='true';const c={registration_open:false,purchases_open:false,maintenance:true,device_wait_days:25};assert.equal((await x.call('settings/controls',patch({...c,device_wait_days:-1}))).status,400);assert.equal((await x.call('settings/controls',patch(c))).status,200);assert.equal((await x.request('/v1/auth/register',{method:'POST',body:{}})).status,403);assert.equal((await x.request('/v1/auth/register/request-code',{method:'POST',body:{}})).status,403);assert.equal((await x.request('/v1/translate',{method:'POST',body:{}})).status,503);assert.equal((await x.login('web')).status,200);const plans=await(await x.request('/v1/billing/plans')).json();assert.equal(plans.paymentsEnabled,false);assert.equal((await x.request('/v1/version')).status,200);});
test('device wait configuration is enforced by database and API',async t=>{const x=fixture(t);const login=await x.login();await x.call('settings/controls',patch({registration_open:true,purchases_open:true,maintenance:false,device_wait_days:30}));x.db.prepare("UPDATE app_device_bindings SET first_seen=strftime('%Y-%m-%dT%H:%M:%fZ','now','-25 days')").run();assert.throws(()=>x.db.prepare('UPDATE app_device_bindings SET revoked=1').run(),/device_binding_locked/);const devices=await(await x.request('/v1/devices',{token:login.token})).json();assert.equal(devices.unbind_wait_days,30);assert.equal(devices.devices[0].can_revoke,false);});
test('compensation is audited, idempotent, positive-only, user-bound and monthly',async t=>{const x=fixture(t),month=new Date().toISOString().slice(0,7);const body={user_id:'alice',year_month:month,amount:345,reason:'异常扣费人工额度补偿',request_id:crypto.randomUUID()};for(const amount of [-1,0,0.1,1000000001])assert.equal((await x.call('compensations',{...body,amount})).status,400);assert.equal((await x.call('compensations',{...body,user_id:'unknown'})).status,404);assert.equal((await x.call('compensations',body)).status,200);assert.equal((await(await x.call('compensations',body)).json()).replayed,true);assert.equal((await x.call('compensations',{...body,amount:346})).status,409);const e=await entitlementSnapshot(x.env,'alice');assert.equal(e.usage.compensation_quota,345);assert.equal(e.usage.base_quota,100345);assert.equal((await entitlementSnapshot(x.env,'bob')).usage.compensation_quota,0);assert.equal((await entitlementSnapshot(x.env,'alice','2099-01-01T00:00:00.000Z')).usage.compensation_quota,0);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM orders').get().n,0);const audit=await(await x.call('audit')).json();assert.match(audit.items[0].kind,/额度补偿/);});
test('feedback progress, internal notes and audit do not expose notes publicly',async t=>{const x=fixture(t);x.db.prepare("INSERT INTO feedback(id,email,category,message,page,created_at,updated_at) VALUES('f1','a@example.com','other','反馈问题描述内容','/','2026-01-01','2026-01-01')").run();const body={kind:'feedback',target_id:'f1',status:'processing',note:'已经联系用户核对信息',request_id:crypto.randomUUID()};assert.equal((await x.call('notes',body)).status,200);assert.equal((await(await x.call('notes',body)).json()).replayed,true);const d=await(await x.call('feedback')).json();assert.equal(d.items[0].workflow_status,'processing');assert.equal(d.items[0].latest_note,body.note);const site=await(await x.request('/v1/site')).json();assert.equal(JSON.stringify(site).includes(body.note),false);assert.equal((await x.call('notes',{...body,target_id:'unknown',request_id:crypto.randomUUID()})).status,404);});
test('order notes cannot mark an order paid and paged read endpoints are read-only',async t=>{const x=fixture(t);assert.equal((await x.call('notes',{kind:'order',target_id:'x',status:'paid',note:'不允许伪造付款结果',request_id:crypto.randomUUID()})).status,400);for(const path of ['orders','devices','usage?q=alice','feedback','audit'])assert.equal((await x.call(path)).status,200);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM orders').get().n,0);});
