import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
const migration=readFileSync(new URL('../migrations/0003_payments.sql',import.meta.url),'utf8').trim();
const upgrade=readFileSync(new URL('../upgrades/0003_payments_from_legacy.sql',import.meta.url),'utf8');
const legacy=`CREATE TABLE orders (order_no TEXT PRIMARY KEY NOT NULL,user_id TEXT NOT NULL,plan_name TEXT NOT NULL DEFAULT 'free',amount_cents INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'CNY',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,paid_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);`;
function setup(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());const schema=readFileSync(new URL('../schema.sql',import.meta.url),'utf8');db.exec(schema.slice(0,schema.indexOf('-- Additive only; current products')));db.exec(legacy);db.exec("INSERT INTO users(id,account,password_hash,created_at) VALUES('u','u','unused','2026-09-14'); INSERT INTO orders(order_no,user_id,plan_name,amount_cents,status,created_at) VALUES('old-paid','u','pro',3900,'paid','2026-09-01'),('old-pending','u','free',0,'pending','2026-09-02'); INSERT INTO usage_monthly VALUES('u','2026-09',321,100000,2);");return db;}
test('legacy upgrade includes the canonical migration',()=>assert.ok(upgrade.trim().endsWith(migration)));
test('legacy upgrade retains every original order field, isolates old payments, leaves quota unchanged',t=>{const db=setup(t);const before=db.prepare('SELECT * FROM orders ORDER BY order_no').all();db.exec(upgrade);for(const row of before){const after=db.prepare('SELECT * FROM orders WHERE order_no=?').get(row.order_no);for(const [k,v] of Object.entries(row))assert.equal(after[k],v);assert.equal(after.provider,'legacy');assert.equal(after.create_state,'legacy');}assert.equal(db.prepare('SELECT chars_used FROM usage_monthly').get().chars_used,321);assert.equal(db.prepare('SELECT COUNT(*) n FROM subscriptions').get().n,0);assert.throws(()=>db.exec("INSERT INTO payment_settlements VALUES('old-paid','fake',3900,'2026-09-14')"),/payment_not_ready/);});
test('upgraded legacy schema supports new idempotent orders and once-only settlement',t=>{const db=setup(t);db.exec(upgrade);const insert="INSERT INTO orders(order_no,user_id,plan_id,plan_name,duration_days,membership_level,amount_cents,payable_cents,channel,idempotency_key,created_at,expires_at) VALUES('new','u','test_pro_019','test',7,'pro',19,19,'alipay','test-key','2026-09-14','2026-09-15') ON CONFLICT(user_id,idempotency_key) DO NOTHING";db.exec(insert);db.exec(insert);assert.equal(db.prepare("SELECT provider FROM orders WHERE order_no='new'").get().provider,'ezfpy');db.exec("UPDATE orders SET provider_trade_no='T1',create_state='ready' WHERE order_no='new'");const settle="INSERT INTO payment_settlements VALUES('new','T1',19,'2026-09-14T00:00:00.000Z') ON CONFLICT(order_no) DO NOTHING";db.exec(settle);db.exec(settle);assert.equal(db.prepare('SELECT expires_at FROM subscriptions').get().expires_at,'2026-09-21T00:00:00.000Z');assert.equal(db.prepare('SELECT COUNT(*) n FROM payment_settlements').get().n,1);assert.equal(db.prepare('SELECT chars_used FROM usage_monthly').get().chars_used,321);assert.equal(db.prepare('SELECT chars_quota FROM usage_monthly').get().chars_quota,1000000);db.exec(migration);assert.equal(db.prepare('SELECT COUNT(*) n FROM orders').get().n,3);});
test('legacy upgrade repetition stops before modifying existing orders',t=>{const db=setup(t);db.exec(upgrade);const before=db.prepare('SELECT * FROM orders').all();assert.throws(()=>db.exec(upgrade),/duplicate column/);assert.deepEqual(db.prepare('SELECT * FROM orders').all(),before);});
