import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
test('real D1: catalog snapshot, Go grants, atomic allocation/refund and duplicate settlement',{timeout:60000},async t=>{
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'catalog-d1',modules:true,script:'export default {fetch(){return new Response("isolated")}}',d1Databases:{DB:'catalog-isolated'},compatibilityDate:'2026-09-13'}]}));t.after(()=>mf.dispose());const DB=await mf.getD1Database('DB','catalog-d1');
 const schema=new DatabaseSync(':memory:');schema.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));const objects=schema.prepare("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'index' THEN 2 ELSE 3 END").all();schema.close();for(const o of objects)await DB.prepare(o.sql).run();
 await DB.prepare("INSERT INTO users(id,account,password_hash,created_at) VALUES('u','u','unused','2026-01-01')").run();await DB.prepare("INSERT INTO plan_catalog(id,name,price_cents,quota,duration_days,enabled,revision,updated_at) VALUES('go','Go',1,50,30,1,1,'2026-01-01')").run();await DB.prepare("INSERT INTO plans VALUES('go','Go',1,30,'pro',1)").run();const at=new Date().toISOString(),ym=at.slice(0,7);
 for(const no of ['g1','g2']){await DB.prepare("INSERT INTO orders(order_no,user_id,plan_id,plan_name,duration_days,membership_level,amount_cents,payable_cents,channel,idempotency_key,created_at,expires_at) VALUES(?,'u','go','Go',30,'go',1,1,'alipay',?,?,?)").bind(no,no,at,at).run();await DB.prepare('INSERT INTO payment_settlements VALUES(?,?,1,?) ON CONFLICT(order_no) DO NOTHING').bind(no,'trade-'+no,at).run();}
 await DB.prepare("INSERT INTO payment_settlements VALUES('g1','trade-g1',1,?) ON CONFLICT(order_no) DO NOTHING").bind(at).run();assert.equal((await DB.prepare('SELECT COUNT(*) n FROM quota_addons').first()).n,2);
 await DB.prepare("INSERT INTO usage_monthly VALUES('u',?,0,10,0)").bind(ym).run();const reserve=id=>DB.prepare("INSERT INTO translation_requests(user_id,request_id,payload_hash,year_month,reserved,expires_at) VALUES('u',?,'hash',?,90,9999999999)").bind(id,ym).run();const results=await Promise.allSettled([reserve('r1'),reserve('r2')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await DB.prepare('SELECT SUM(amount) n FROM addon_allocations').first()).n,80);
 await DB.prepare("UPDATE translation_requests SET billed=75,state='settled'").run();assert.equal((await DB.prepare('SELECT SUM(amount) n FROM addon_allocations').first()).n,65);assert.equal((await DB.prepare('SELECT SUM(remaining) n FROM addon_balances').first()).n,35);assert.equal((await DB.prepare('SELECT chars_used n FROM usage_monthly').first()).n,75);
});

