import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/worker.mjs';

test('web login creates a scoped session and no APP binding',async t=>{const x=setup(t);const a=await x.login('web');assert.equal(a.status,200);assert.ok(a.token);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings').get().n,0);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM devices').get().n,0);assert.equal((await x.request('/v1/profile',{token:a.token})).status,200);const list=await(await x.request('/v1/devices',{token:a.token})).json();assert.equal(list.used_devices,0);});
test('three APP bindings do not prevent multiple browser logins; fourth APP denied',async t=>{const x=setup(t);for(let i=0;i<3;i++)assert.equal((await x.login('app','d'+i)).status,200);for(let i=0;i<4;i++)assert.equal((await x.login('web','web-'+i)).status,200);assert.equal((await x.login('app','fourth')).status,403);assert.equal((await x.login('app','d0')).status,200);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings').get().n,3);});
test('same installation can bind two accounts and revocation is account-scoped',async t=>{const x=setup(t),a=await x.login(),b=await x.login('app','install-1','bob'),web=await x.login('web');assert.equal(b.status,200);assert.equal((await x.request('/v1/devices/revoke',{method:'POST',token:web.token,body:{device_id:'install-1'}})).status,200);assert.equal((await x.request('/v1/profile',{token:a.token})).status,401);assert.equal((await x.request('/v1/profile',{token:b.token})).status,200);assert.equal((await x.request('/v1/profile',{token:web.token})).status,200);});
test('web cannot execute translation or bind an arbitrary device',async t=>{const x=setup(t),a=await x.login('web');for(const path of ['/v1/translate','/v1/devices/bind']){const r=await x.request(path,{method:'POST',token:a.token,body:{device_id:'anything'}});assert.equal(r.status,403);assert.equal((await r.json()).error_code,'app_binding_required');}});
test('APP can confirm only its own binding',async t=>{const x=setup(t),a=await x.login();assert.equal((await x.request('/v1/devices/bind',{method:'POST',token:a.token,body:{device_id:'another'}})).status,403);const r=await x.request('/v1/devices/bind',{method:'POST',token:a.token,body:{device_id:'install-1',device_name:'Renamed'}});assert.equal(r.status,200);assert.equal((await r.json()).used_devices,1);});
test('logout invalidates only current session and keeps binding',async t=>{const x=setup(t),a=await x.login(),b=await x.login();assert.equal((await x.request('/v1/auth/logout',{method:'POST',token:a.token})).status,200);assert.equal((await x.request('/v1/profile',{token:a.token})).status,401);assert.equal((await x.request('/v1/profile',{token:b.token})).status,200);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings WHERE revoked=0').get().n,1);});
test('concurrent fourth bindings cannot overdraw and cannot leave orphan sessions',async t=>{const x=setup(t);await x.login('app','d1');await x.login('app','d2');const results=await Promise.all([x.login('app','d3'),x.login('app','d4')]);assert.deepEqual(results.map(x=>x.status).sort(),[200,403]);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM sessions').get().n,3);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM session_contexts').get().n,3);});
test('concurrent repeated login at quota remains one binding',async t=>{const x=setup(t);for(let i=1;i<=3;i++)await x.login('app','d'+i);const results=await Promise.all([x.login('app','d1'),x.login('app','d1')]);assert.ok(results.every(x=>x.status===200));assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings').get().n,3);});
test('reactivation at quota is rejected by database, identity cannot be reassigned',async t=>{const x=setup(t);await x.login();x.db.exec('UPDATE app_device_bindings SET revoked=1');for(let i=0;i<3;i++)await x.login('app','d'+i);assert.equal((await x.login()).status,403);assert.throws(()=>x.db.exec("UPDATE app_device_bindings SET revoked=0 WHERE device_id='install-1'"),/device_limit/);assert.throws(()=>x.db.exec("UPDATE app_device_bindings SET user_id='bob'"),/binding_identity_immutable/);});
test('expired, malformed expiry, inactive and unclassified sessions fail closed',async t=>{for(const sql of ["UPDATE sessions SET expires_at='2000-01-01'","UPDATE sessions SET expires_at='invalid'","UPDATE users SET is_active=0","DELETE FROM session_contexts"]){const x=setup(t),a=await x.login();x.db.exec(sql);assert.equal((await x.request('/v1/profile',{token:a.token})).status,401);}});
test('old browser IDs cannot use legacy APP login',async t=>{const x=setup(t);assert.equal((await x.login('app','web-browser')).status,400);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);});
test('revoking another account device has no effect',async t=>{const x=setup(t),a=await x.login('web'),b=await x.login('app','bob-device','bob');assert.equal((await x.request('/v1/devices/revoke',{method:'POST',token:a.token,body:{device_id:'bob-device'}})).status,404);assert.equal((await x.request('/v1/profile',{token:b.token})).status,200);});
test('rebind does not resurrect sessions that were revoked',async t=>{const x=setup(t),a=await x.login(),web=await x.login('web');await x.request('/v1/devices/revoke',{method:'POST',token:web.token,body:{device_id:'install-1'}});const b=await x.login();assert.equal(b.status,200);assert.equal((await x.request('/v1/profile',{token:a.token})).status,401);assert.equal((await x.request('/v1/profile',{token:b.token})).status,200);});
test('web scope cannot be elevated by a client platform or APP device id',async t=>{const x=setup(t);const response=await x.request('/v1/auth/web/login',{method:'POST',body:{account:'alice',password:x.password,device_id:'spoof',platform:'Windows',client_kind:'app'}});assert.equal(response.status,200);const {token}=await response.json();assert.equal((await x.request('/v1/translate',{method:'POST',token,body:{items:[]}})).status,403);});
test('profile PATCH persists display name but cannot change verified identity',async t=>{const x=setup(t),a=await x.login('web');let r=await x.request('/v1/profile',{method:'PATCH',token:a.token,body:{display_name:'New name',email:'alice@example.com'}});assert.equal(r.status,200);assert.equal((await(await x.request('/v1/profile',{token:a.token})).json()).display_name,'New name');r=await x.request('/v1/profile',{method:'PATCH',token:a.token,body:{display_name:'X',email:'other@example.com'}});assert.equal(r.status,400);assert.equal(x.db.prepare("SELECT email FROM users WHERE id='alice'").get().email,'alice@example.com');});
test('password change checks old password then revokes every account session, not bindings',async t=>{const x=setup(t),a=await x.login('web'),b=await x.login();assert.equal((await x.request('/v1/auth/password',{method:'PATCH',token:a.token,body:{current_password:'wrong',new_password:'NewPassword1!'}})).status,400);assert.equal((await x.request('/v1/profile',{token:b.token})).status,200);assert.equal((await x.request('/v1/auth/password',{method:'PATCH',token:a.token,body:{current_password:x.password,new_password:'NewPassword1!'}})).status,200);for(const token of [a.token,b.token])assert.equal((await x.request('/v1/profile',{token})).status,401);assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings WHERE revoked=0').get().n,1);});
import {issueSession} from '../src/auth/sessions.ts';
test('password reset between credential check and session batch cannot mint a new login or binding',async t=>{
 const x=setup(t), old=x.db.prepare("SELECT password_hash FROM users WHERE id='alice'").get().password_hash;
 x.db.exec("UPDATE users SET password_hash='changed' WHERE id='alice'");
 for(const kind of ['app','web'])await assert.rejects(issueSession(x.env,'alice',kind,old,'new-device'),/session_credentials_changed/);
 assert.equal(x.db.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);
 assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings').get().n,0);
});
test('account disabled before session commit cannot acquire a binding',async t=>{
 const x=setup(t), old=x.db.prepare("SELECT password_hash FROM users WHERE id='alice'").get().password_hash;
 x.db.exec("UPDATE users SET is_active=0 WHERE id='alice'");
 await assert.rejects(issueSession(x.env,'alice','app',old,'new-device'),/session_credentials_changed/);
 assert.equal(x.db.prepare('SELECT COUNT(*) n FROM app_device_bindings').get().n,0);
});
