import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {pbkdf2Sync,createHash} from 'node:crypto';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';

test('real workerd/D1: logout, device revoke/rebind and password-reset transaction lifecycle',{timeout:60000},async t=>{
 const code=await build({stdin:{contents:`import worker from './src/index.ts'; globalThis.fetch=()=>{throw new Error('external network forbidden');}; export default worker;`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'ts'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});
 const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'session-lifecycle',modules:true,script:code.outputFiles[0].text,d1Databases:{DB:'session-lifecycle-isolated'},bindings:{PASSWORD_PEPPER:'test-only'},compatibilityDate:'2026-09-13'}]}));
 t.after(()=>mf.dispose());
 const DB=await mf.getD1Database('DB','session-lifecycle');
 const schema=new DatabaseSync(':memory:');schema.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
 const objects=schema.prepare("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END").all();schema.close();
 for(const o of objects)await DB.prepare(o.sql).run();
 const password='ExamplePassword1!',salt='test-salt';
 const hash='v2:'+salt+':'+pbkdf2Sync(password+'\\0'+'test-only',salt,100000,32,'sha256').toString('hex');
 for(const id of ['alice','bob'])await DB.prepare('INSERT INTO users(id,account,email,password_hash,created_at) VALUES(?,?,?,?,?)').bind(id,id,id+'@example.com',hash,new Date().toISOString()).run();
 const request=(path,{method='GET',body,token}={})=>mf.dispatchFetch('https://local.test'+path,{method,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const login=async(kind='app',account='alice',pw=password)=>{const r=await request('/v1/auth/'+(kind==='web'?'web/login':'login'),{method:'POST',body:{account,password:pw,device_id:'install-1'}});assert.equal(r.status,200);return (await r.json()).token;};
 const status=async(token,expected)=>assert.equal((await request('/v1/profile',{token})).status,expected);
 let app=await login(),web=await login('web');const bob=await login('app','bob');
 assert.equal((await request('/v1/auth/logout',{method:'POST',token:app})).status,200);
 await status(app,401);await status(web,200);await status(bob,200);
 app=await login();
 await DB.prepare("UPDATE app_device_bindings SET first_seen='2000-01-01'").run();
 assert.equal((await request('/v1/devices/revoke',{method:'POST',token:web,body:{device_id:'install-1'}})).status,200);
 await status(app,401);await status(web,200);await status(bob,200);
 const rebound=await login();await status(rebound,200);await status(app,401);
 const id=crypto.randomUUID(),verification='123456';
 const codeHash=createHash('sha256').update(verification+'|alice@example.com|password_reset').digest('hex');
 await DB.prepare('INSERT INTO email_verification_codes(id,email,purpose,code_hash,expires_at,created_at) VALUES(?,?,?,?,?,?)').bind(id,'alice@example.com','password_reset',codeHash,new Date(Date.now()+600000).toISOString(),new Date().toISOString()).run();
 const reset=(new_password)=>request('/v1/auth/password/reset',{method:'POST',body:{email:'alice@example.com',code:verification,new_password}});
 await DB.prepare("CREATE TRIGGER fail_session_revoke BEFORE UPDATE OF revoked_at ON sessions BEGIN SELECT RAISE(ABORT,'controlled failure'); END").run();
 assert.equal((await reset('CandidatePassword1!')).status,500);
 assert.equal((await DB.prepare('SELECT used_at FROM email_verification_codes WHERE id=?').bind(id).first()).used_at,null);
 assert.equal((await DB.prepare("SELECT password_hash FROM users WHERE id='alice'").first()).password_hash,hash);
 await status(rebound,200);await status(web,200);
 await DB.prepare('DROP TRIGGER fail_session_revoke').run();
 const passwords=['CandidatePassword1!','CandidatePassword2!'];
 const resets=await Promise.all(passwords.map(reset));assert.deepEqual(resets.map(r=>r.status).sort(),[200,400]);
 await status(rebound,401);await status(web,401);await status(bob,200);
 const winner=resets.findIndex(r=>r.status===200);await status(await login('web','alice',passwords[winner]),200);
 const old=await request('/v1/auth/web/login',{method:'POST',body:{account:'alice',password}});assert.equal(old.status,401);
 assert.equal((await reset(passwords[winner])).status,400);
 assert.equal((await DB.prepare('SELECT COUNT(*) n FROM translation_requests').first()).n,0);
 assert.equal((await DB.prepare('SELECT COUNT(*) n FROM orders').first()).n,0);
});
