interface Env { DB: D1Database; DEEPSEEK_API_KEY: string; JWT_SECRET: string; PASSWORD_PEPPER: string; ADMIN_API_KEY: string; CORS_ORIGINS?: string; DEFAULT_PLAN?: string; MAX_TRANSLATE_ITEMS?: string; MAX_TEXT_LENGTH?: string; SESSION_TTL_DAYS?: string; }
type J = Record<string, any>;
const now=()=>new Date().toISOString();
const json=(x:any,status=200,origin='*')=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,OPTIONS'}});
const cors=(env:Env)=>env.CORS_ORIGINS||'https://cad.pocketter.dpdns.org';
const text=async(r:Request)=>{try{return await r.json() as J}catch{return null}};
const random=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
async function digest(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function pass(p:string,pepper:string){const b=await crypto.subtle.importKey('raw',new TextEncoder().encode(p+'\\0'+pepper),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode('dwgc2e-password-v1'),iterations:120000,hash:'SHA-256'},b,256);return [...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')+':pbkdf2';}
async function auth(r:Request,e:Env){const h=r.headers.get('authorization')||'';const t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return null;const row=await e.DB.prepare('SELECT s.user_id,s.device_id,u.account,u.display_name,u.email,u.is_active,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL').bind(await digest(t)).first<J>();if(!row||!row.is_active||new Date(row.expires_at)<=new Date())return null;return row;}
function quota(e:Env){return Number(e.DEFAULT_PLAN==='free'?100000:1000000)}
async function register(r:Request,e:Env){const b=await text(r);const account=String(b?.account||'').trim(),password=String(b?.password||'');if(account.length<3||password.length<8)return json({success:false,error_code:'invalid_request',message:'账号至少 3 位，密码至少 8 位'},400,cors(e));if(await e.DB.prepare('SELECT 1 FROM users WHERE account=?').bind(account).first())return json({success:false,error_code:'account_exists',message:'账号已存在'},409,cors(e));const id=random(),ts=now();await e.DB.batch([e.DB.prepare('INSERT INTO users(id,account,password_hash,display_name,email,created_at) VALUES(?,?,?,?,?,?)').bind(id,account,await pass(password,e.PASSWORD_PEPPER),String(b.display_name||account),String(b.email||account),ts),e.DB.prepare('INSERT INTO subscriptions(user_id,plan_name,starts_at,updated_at) VALUES(?,?,?,?)').bind(id,e.DEFAULT_PLAN||'free',ts,ts)]);return json({success:true,message:'注册成功，请登录'},201,cors(e));}
async function login(r:Request,e:Env){const b=await text(r);if(!b?.account||!b?.password)return json({success:false,error_code:'invalid_request',message:'账号和密码不能为空'},400,cors(e));const u=await e.DB.prepare('SELECT * FROM users WHERE account=?').bind(String(b.account).trim()).first<J>();if(!u||u.password_hash!==(await pass(String(b.password),e.PASSWORD_PEPPER)))return json({success:false,error_code:'invalid_credentials',message:'账号或密码错误'},401,cors(e));const device=String(b.device_id||'unknown');const count=await e.DB.prepare('SELECT COUNT(*) n FROM devices WHERE user_id=? AND revoked=0').bind(u.id).first<J>();if(!await e.DB.prepare('SELECT 1 FROM devices WHERE user_id=? AND device_id=?').bind(u.id,device).first() && Number(count?.n||0)>=3)return json({success:false,error_code:'device_limit',message:'设备数量已达到套餐上限'},403,cors(e));const token=random(), expires=new Date(Date.now()+Number(e.SESSION_TTL_DAYS||30)*86400000).toISOString(), ts=now();await e.DB.batch([e.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,device_id,expires_at,created_at) VALUES(?,?,?,?,?,?)').bind(random(),u.id,await digest(token),device,expires,ts),e.DB.prepare('INSERT INTO devices(device_id,user_id,device_name,platform,first_seen,last_seen) VALUES(?,?,?,?,?,?) ON CONFLICT(device_id) DO UPDATE SET last_seen=excluded.last_seen,device_name=excluded.device_name').bind(device,u.id,String(b.device_name||''),e.DEVICE_PLATFORM||'Windows',ts,ts)]);return json({success:true,token,expires_at:expires},200,cors(e));}
async function translate(r:Request,e:Env,user:J){const b=await text(r);const items=Array.isArray(b?.items)?b.items:[];if(!items.length||items.length>Number(e.MAX_TRANSLATE_ITEMS||100))return json({success:false,error_code:'invalid_request',message:'翻译条目数量无效'},400,cors(e));const clean=items.map(x=>({id:Number(x.id),text:String(x.text||'').slice(0,Number(e.MAX_TEXT_LENGTH||2000))}));const chars=clean.reduce((n,x)=>n+x.text.length,0);const ym=now().slice(0,7);const u=await e.DB.prepare('SELECT chars_used,chars_quota FROM usage_monthly WHERE user_id=? AND year_month=?').bind(user.user_id,ym).first<J>();if(Number(u?.chars_used||0)+chars>Number(u?.chars_quota||quota(e)))return json({success:false,error_code:'quota_exceeded',message:'本月翻译额度不足'},402,cors(e));const prompt=`Translate CAD drawing text from ${b.source_lang} to ${b.target_lang}. Return ONLY a JSON array of objects with id and translated_text. Preserve numbers, dimensions, tolerances, model numbers and format. Items: ${JSON.stringify(clean)}`;let response:Response;try{response=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${e.DEEPSEEK_API_KEY}`},body:JSON.stringify({model:'deepseek-chat',temperature:0.1,messages:[{role:'system',content:'You translate technical CAD labels accurately.'},{role:'user',content:prompt}]})});}catch{return json({success:false,error_code:'upstream_unavailable',message:'翻译服务暂时不可用'},503,cors(e));}if(!response.ok)return json({success:false,error_code:'upstream_unavailable',message:'翻译服务暂时不可用'},503,cors(e));const d=await response.json() as J;let out:any[]=[];try{out=JSON.parse(String(d.choices?.[0]?.message?.content||'[]').replace(/^```json\s*|```$/g,''))}catch{}const result=clean.map(x=>{const z=out.find(y=>Number(y.id)===x.id);return z?.translated_text?{id:x.id,translated_text:String(z.translated_text),from_cache:false}:{id:x.id,error_code:'missing_result'}});await e.DB.prepare('INSERT INTO usage_monthly(user_id,year_month,chars_used,chars_quota,task_count) VALUES(?,?,?,?,1) ON CONFLICT(user_id,year_month) DO UPDATE SET chars_used=chars_used+excluded.chars_used,task_count=task_count+1').bind(user.user_id,ym,chars,Number(u?.chars_quota||quota(e))).run();return json({success:true,characters_used:chars,cached_count:0,items:result},200,cors(e));}
export default {async fetch(r:Request,e:Env){const origin=cors(e);if(r.method==='OPTIONS')return json({},204,origin);const u=new URL(r.url),p=u.pathname;if(p==='/'&&r.method==='GET')return json({service:'DWGC2E API',status:'ok',version:'0.1.0'},200,origin);if(p==='/v1/auth/register'&&r.method==='POST')return register(r,e);if(p==='/v1/auth/login'&&r.method==='POST')return login(r,e);if(p==='/v1/version'&&r.method==='GET')return json({latest_version:'2.1.0',download_url:'https://cad.pocketter.dpdns.org',backup_download_url:'',release_notes:'',mandatory:false},200,origin);const user=await auth(r,e);if(!user)return json({error_code:'unauthenticated',message:'请先登录'},401,origin);if(p==='/v1/profile')return json({display_name:user.display_name||user.account,email:user.email||user.account,is_active:true},200,origin);if(p==='/v1/subscription')return json({plan_name:e.DEFAULT_PLAN==='free'?'免费版':'专业版',starts_at:null,expires_at:null,auto_renew:false,entitlements:[]},200,origin);if(p==='/v1/usage'){const ym=now().slice(0,7),x=await e.DB.prepare('SELECT chars_used,chars_quota FROM usage_monthly WHERE user_id=? AND year_month=?').bind(user.user_id,ym).first<J>();return json({monthly_quota:Number(x?.chars_quota||quota(e)),used:Number(x?.chars_used||0),reset_at:new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth()+1,1)).toISOString()},200,origin)}if(p==='/v1/devices/bind'&&r.method==='POST')return json({success:true,used_devices:Number((await e.DB.prepare('SELECT COUNT(*) n FROM devices WHERE user_id=? AND revoked=0').bind(user.user_id).first<J>())?.n||0),max_devices:3},200,origin);if(p==='/v1/translate'&&r.method==='POST')return translate(r,e,user);return json({error_code:'not_found',message:'接口不存在'},404,origin)}};


